"""add profile engagement procedure fields

Revision ID: 035daf1517e0
Revises: 58a2646e4449
Create Date: 2026-09-29 01:11:18.504590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035daf1517e0'
down_revision: Union[str, None] = '58a2646e4449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default="[]" on the JSON columns: existing rows (from scans
    # run before this migration) get backfilled with an empty list instead
    # of failing the NOT NULL constraint. Dropped again below so newly
    # inserted rows go through the ORM's own default=list instead of
    # relying on the DB default long-term.
    op.add_column('job_observations', sa.Column('education', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('job_observations', sa.Column('experience', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('job_observations', sa.Column('skills', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('job_observations', sa.Column('methods', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('job_observations', sa.Column('certifications', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('job_observations', sa.Column('languages', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('job_observations', sa.Column('contract_type', sa.Text(), nullable=True))
    op.add_column('job_observations', sa.Column('zzp_allowed', sa.Boolean(), nullable=True))
    op.add_column('job_observations', sa.Column('screening', sa.Text(), nullable=True))
    op.add_column('job_observations', sa.Column('vog', sa.Boolean(), nullable=True))
    op.add_column('job_observations', sa.Column('positions', sa.Integer(), nullable=True))
    op.add_column('job_observations', sa.Column('max_candidates', sa.Integer(), nullable=True))
    op.add_column('jobs_current', sa.Column('education', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('jobs_current', sa.Column('experience', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('jobs_current', sa.Column('skills', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('jobs_current', sa.Column('methods', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('jobs_current', sa.Column('certifications', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('jobs_current', sa.Column('languages', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('jobs_current', sa.Column('contract_type', sa.Text(), nullable=True))
    op.add_column('jobs_current', sa.Column('zzp_allowed', sa.Boolean(), nullable=True))
    op.add_column('jobs_current', sa.Column('screening', sa.Text(), nullable=True))
    op.add_column('jobs_current', sa.Column('vog', sa.Boolean(), nullable=True))
    op.add_column('jobs_current', sa.Column('positions', sa.Integer(), nullable=True))
    op.add_column('jobs_current', sa.Column('max_candidates', sa.Integer(), nullable=True))

    # Drop the server-side defaults now that existing rows are backfilled —
    # going forward, JobRepository always supplies these values explicitly
    # (JobNormalizer/LlmFieldExtractor), so the DB default would otherwise
    # silently mask a bug where the ORM forgot to set one.
    for table in ("job_observations", "jobs_current"):
        for column in ("education", "experience", "skills", "methods", "certifications", "languages"):
            op.alter_column(table, column, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs_current', 'max_candidates')
    op.drop_column('jobs_current', 'positions')
    op.drop_column('jobs_current', 'vog')
    op.drop_column('jobs_current', 'screening')
    op.drop_column('jobs_current', 'zzp_allowed')
    op.drop_column('jobs_current', 'contract_type')
    op.drop_column('jobs_current', 'languages')
    op.drop_column('jobs_current', 'certifications')
    op.drop_column('jobs_current', 'methods')
    op.drop_column('jobs_current', 'skills')
    op.drop_column('jobs_current', 'experience')
    op.drop_column('jobs_current', 'education')
    op.drop_column('job_observations', 'max_candidates')
    op.drop_column('job_observations', 'positions')
    op.drop_column('job_observations', 'vog')
    op.drop_column('job_observations', 'screening')
    op.drop_column('job_observations', 'zzp_allowed')
    op.drop_column('job_observations', 'contract_type')
    op.drop_column('job_observations', 'languages')
    op.drop_column('job_observations', 'certifications')
    op.drop_column('job_observations', 'methods')
    op.drop_column('job_observations', 'skills')
    op.drop_column('job_observations', 'experience')
    op.drop_column('job_observations', 'education')
    # ### end Alembic commands ###
