"""initial schema

This migration is intentionally empty: it was generated with
--autogenerate against the already-running database whose schema was
built by JobRepository.create_schema() (Base.metadata.create_all()) plus
hand-applied ALTER TABLEs, and it matched the current models exactly —
there was nothing left to generate. It exists purely as the root revision
(down_revision=None) so every schema change from now on is a real,
reviewable migration instead of another manual ALTER TABLE. Applied via
`alembic stamp head` (not `upgrade`), since there is nothing to run and
running it against a fresh empty database would leave every table
missing — use `Base.metadata.create_all()` for a fresh database, then
`alembic stamp head`, then real migrations from here on.

Revision ID: 0a5006f20da8
Revises:
Create Date: 2026-09-28 23:45:57.512186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5006f20da8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
