"""add source_hash to jobs_current

Revision ID: 2572ad287c49
Revises: 035daf1517e0
Create Date: 2026-09-29 11:23:40.302380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2572ad287c49'
down_revision: Union[str, None] = '035daf1517e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs_current', sa.Column('source_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs_current', 'source_hash')
    # ### end Alembic commands ###
