"""initial schema

Creates every table the pipeline needs: job_observations, jobs_current,
scan_runs, scan_routes, scan_errors. This is the root revision
(down_revision=None) — running `alembic upgrade head` against a fresh,
empty database builds the full schema from scratch. Every schema change
from here on is a real, reviewable migration instead of a manual
ALTER TABLE.

The already-running database (which had this exact schema built by
JobRepository.create_schema() plus hand-applied ALTER TABLEs before
Alembic was introduced) was brought under Alembic via
`alembic stamp <revision>` instead of `upgrade` — its tables already
existed, so upgrade() was never actually run against it. `alembic check`
confirms zero drift between this migration and that database.

Revision ID: 58a2646e4449
Revises:
Create Date: 2026-09-28 23:51:49.457378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a2646e4449'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('rate', sa.Text(), nullable=True),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('segment', sa.Text(), nullable=True),
    sa.Column('hours_per_week', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('description_original', sa.Text(), nullable=True),
    sa.Column('hard_requirements', sa.JSON(), nullable=False),
    sa.Column('wishes', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_observations_scan_id'), 'job_observations', ['scan_id'], unique=False)
    op.create_index(op.f('ix_job_observations_source_job_id'), 'job_observations', ['source_job_id'], unique=False)
    op.create_table('jobs_current',
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('rate', sa.Text(), nullable=True),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('segment', sa.Text(), nullable=True),
    sa.Column('hours_per_week', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('description_original', sa.Text(), nullable=True),
    sa.Column('hard_requirements', sa.JSON(), nullable=False),
    sa.Column('wishes', sa.JSON(), nullable=False),
    sa.Column('rate_min', sa.Integer(), nullable=True),
    sa.Column('rate_max', sa.Integer(), nullable=True),
    sa.Column('hours_min', sa.Integer(), nullable=True),
    sa.Column('hours_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('consecutive_absences', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source_job_id')
    )
    op.create_table('scan_runs',
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.String(length=128), nullable=False),
    sa.Column('dedup_rule', sa.String(length=128), nullable=False),
    sa.Column('scan_status', sa.String(length=32), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_reason', sa.Text(), nullable=True),
    sa.Column('count_discovered', sa.Integer(), nullable=False),
    sa.Column('count_processed', sa.Integer(), nullable=False),
    sa.Column('count_duplicates', sa.Integer(), nullable=False),
    sa.Column('count_new', sa.Integer(), nullable=False),
    sa.Column('count_changed', sa.Integer(), nullable=False),
    sa.Column('count_closed', sa.Integer(), nullable=False),
    sa.Column('count_temporarily_not_found', sa.Integer(), nullable=False),
    sa.Column('count_errors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_table('scan_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('recovery_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_runs.scan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_errors_scan_id'), 'scan_errors', ['scan_id'], unique=False)
    op.create_table('scan_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('pages_visited', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_runs.scan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_routes_scan_id'), 'scan_routes', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_routes_scan_id'), table_name='scan_routes')
    op.drop_table('scan_routes')
    op.drop_index(op.f('ix_scan_errors_scan_id'), table_name='scan_errors')
    op.drop_table('scan_errors')
    op.drop_table('scan_runs')
    op.drop_table('jobs_current')
    op.drop_index(op.f('ix_job_observations_source_job_id'), table_name='job_observations')
    op.drop_index(op.f('ix_job_observations_scan_id'), table_name='job_observations')
    op.drop_table('job_observations')
    # ### end Alembic commands ###
